# -*- coding: utf-8 -*-
"""FlaskApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kDIozo00f0am95fJxIhfFsUN5dKaAgUp
"""

import numpy as np
import pickle
import pandas as pd
from flask import Flask, request
from flask import Flask, request, jsonify, render_template

app=Flask(__name__)
pickle_in = open("Wheatclassifier.pkl","rb")
classifier=pickle.load(pickle_in)

@app.route('/')
#def hello():
#    return "This is a APP Creation Test"
def home():
    return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():
    '''
    For rendering results on HTML GUI
    '''
    int_features = [x for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction = classifier.predict(final_features)
    
    return render_template('index.html', prediction_text='The Wheat belong to Kernel type {}'.format(prediction))

#@app.route('/predict')
#def predict_class():
#    Area=request.args.get('Area')
#    Perimeter=request.args.get('Perimeter')
#    Compactness=request.args.get('Compactness')
#    Kernellength=request.args.get('Kernellength')
#    Kernelwidth=request.args.get('Kernelwidth')
#    Asymmetry=request.args.get('Asymmetry')
#    Kernelgroove=request.args.get('Kernelgroove')
    
#    prediction=classifier.predict([[Area,Perimeter,Compactness,Kernellength,Kernelwidth,Asymmetry,Kernelgroove]])
#    return " The Predicted Class is"+ str(prediction)

if __name__=='__main__':
    app.run()